COMPONENT=ChildNodesAppC
CFLAGS += -I$(TOS_OS_DIR)/lib/printf
CFLAGS += -DNEW_PRINTF_SEMANTICS
CFLAGS += -DPRINTF_BUFFER_SIZE=10

TINYOS_ROOT_DIR?=~/Downloads/backup/Softwares/tinyos-main/git-repo/test/symbmote
include $(TINYOS_ROOT_DIR)/Makefile.include
